---
# Proxy Networking Stack
# Networking proxy stack including Traefik load balancer and Whoami for testing.

networks:
  traefik-dev:


services:
  # TRAEFIK - LOAD BALANCER / SSL / WEB SERVER
  traefik:
    container_name: traefik
    image: traefik:2.2
    restart: always
    networks:
      - traefik-dev
    ports:
      - target: 8181
        published: 8080
        protocol: tcp
        mode: host
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    deploy:
      placement:
        constraints:
          - node.role == manager

  whoami:
    image: "traefik/whoami:1.11.0"
    networks:
      - traefik-dev
