api:
  dashboard: true
  insecure: true # FIXME: Needs to work while secure
  debug: true # TODO: Disable in production

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      middlewares:
        - "https-redirect@docker"
      tls:
        certResolver: myresolver

providers:
  swarm:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik-development # TODO: Change to traefik-production in production

certificatesResolvers:
  # TODO: Change myresolver to something more specific in production
  myresolver:
    acme:
      email: ${ACME_EMAIL}
      storage: /data/acme.json
      tlsChallenge: {}
