---
# /roles/stack-networking-proxy/tasks/main.yml

- name: Render docker compose for Traefik
  ansible.builtin.template:
    src: docker-compose.{{ stack.name }}.yml.j2
    dest: "{{ role_path }}/files/docker-compose.{{ stack.name }}.yml"
    mode: "0644"
