services:
  traefik:
    image: traefik:v3.5.3
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
  configs:
    - source: app_config
      target: /etc/myapp/config.yaml
  whoami:
    image: traefik/whoami:v1.11.0
    ports:
      - target: 80
        published: 8081
        protocol: tcp
        mode: host
  configs:
    - source: app_config
      target: /etc/myapp/config.yaml

configs:
  app_config:
    file: ./configs/app_config.yml
