---
# roles/stack-networking-proxy/vars/main.yml

stack:
  name: proxy-networking-stack
  full_name: "Proxy Networking Stack"
  description: "Networking proxy stack including Traefik load balancer and Whoami for testing."

traefik:
  version: "2.2"
  network: traefik-dev
  expose_internally: true
  expose_externally: true
  https_only: true
  service_domain: "traefik.{{ domain.base }}"
  acme:
    email: shackofnoreturn@gmail.com
    resolver: cloudflare
    storage: /letsencrypt/acme.json

whoami:
  version: "v1.11.0"
