services:
  wikidb:
    image: postgres:15
    environment:
      POSTGRES_DB: wikijs
      POSTGRES_USER: wikijs
      POSTGRES_PASSWORD: ${DB_PASS}
    logging:
      driver: none
    restart: unless-stopped
    volumes:
      - wikidb-data:/var/lib/postgresql/data

  wikijs:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - wikidb
    environment:
      DB_TYPE: postgres
      DB_HOST: wikidb
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: ${DB_PASS}
      DB_NAME: wikijs
      # Database SSL/HTTPS support
      # DB_SSL: true
      # DB_SSL_CA: /path/to/ca.pem

      # Let's Encrypt support 
      #  Exposed HTTPS port is 3443
      #  Both HTTP and HTTPS ports must be exposed when using Let's Encrypt
      # SSL_ACTIVE: true
      # LETSENCRYPT_DOMAIN: wiki.example.com
      # LETSENCRYPT_EMAIL:
      
      # When running multiple replicas
      # HA_ACTIVE: true
    restart: unless-stopped
    ports:
      - 80:3000
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.wikijs.rule=Host(`${WIKI_DOMAIN}`)"
    #   - "traefik.http.routers.wikijs.entrypoints=websecure"
    #   - "traefik.http.routers.wikijs.tls.certresolver=${TRAEFIK_RESOLVER}"
    #   - "traefik.http.services.wikijs.loadbalancer.server.port=3000"

  drawio:
    image: jgraph/drawio
    restart: unless-stopped
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.drawio.rule=Host(`${DRAWIO_DOMAIN}`)"
    #   - "traefik.http.routers.drawio.entrypoints=websecure"
    #   - "traefik.http.routers.drawio.tls.certresolver=${TRAEFIK_RESOLVER}"
    #   - "traefik.http.services.drawio.loadbalancer.server.port=8080"

volumes:
  wikidb-data:
