---
- name: Clean existing stack folder
  ansible.builtin.file:
    path: "{{ project_root }}/{{ stack_item.value.name }}"
    state: absent
  when: cleanup == true | default(false)

- name: Ensure stack directory and subdirectories exist
  ansible.builtin.file:
    path: "{{ project_root }}/{{ stack_item.value.name }}/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - configs

- name: Find all template files
  ansible.builtin.find:
    paths: "{{ template_path }}"
    recurse: yes
    file_type: file
  register: template_files

- name: Render template templates
  ansible.builtin.template:
    src: "{{ item.path }}"
    dest: >-
      {{ project_root }}/{{ stack_item.value.name }}/{{ item.path | regex_replace('^' ~ template_path ~ '/', '') | regex_replace('.j2$', '') }}
  loop: "{{ template_files.files }}"
  loop_control:
    label: "{{ item.path | basename }}"
  vars:
    stack: "{{ stack_item.value }}"
