---
- name: Create all stacks
  hosts: localhost
  vars_files:
    - ../stacks.yml
  vars:
    project_root: "../stacks"
    template_path: "../stack-template"
    cleanup: false

  tasks:
    - name: Loop through all stacks
      include_tasks: create_one.yml
      loop: "{{ stacks | dict2items }}"
      loop_control:
        loop_var: stack_item
