---
# playbooks/stacks-all.yml

- name: Complete Stacks Procedure
  playbooks:
    - stacks-render.yml
    # - stacks-push.yml
    # - stacks-stop.yml
    # - stacks-remove.yml
    - stacks-deploy.yml
    # - stacks-migrate.yml