---
# playbooks/stacks-all.yml
  
- import_playbook: playbooks/stacks-render.yml
- import_playbook: playbooks/stacks-push.yml
- import_playbook: playbooks/stacks-deploy.yml
- import_playbook: playbooks/stacks-stop.yml
- import_playbook: playbooks/stacks-start.yml
- import_playbook: playbooks/stacks-remove.yml
