---
# playbooks/stacks-all.yml

- name: Complete Stacks Procedure
  playbook:
    - stacks-render.yml
    # - stacks-push.yml
    - stacks-deploy.yml
    - stacks-stop.yml
    - stacks-start.yml
    - stacks-remove.yml
  