---
# playbooks/stacks-remove.yml

- name: Removes all Portainer stacks
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    target_stack: stack-networking-proxy
  roles:
    - portainer-remove
